# Generated by Django 4.2 on 2023-07-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_User_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_or_husband_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(default='1901-01-01')),
                ('mobile_no1', models.CharField(blank=True, max_length=15)),
                ('mobile_no2', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('active_flag', models.CharField(choices=[('Sifted', 'Sifted'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('delete_flag', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('death_flag', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('receipt_no', models.CharField(blank=True, max_length=20)),
                ('receipt_date', models.DateField(default='2001-11-1')),
                ('area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mapp.area')),
                ('village', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mapp.village')),
            ],
        ),
    ]
