# Generated by Django 4.2 on 2023-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_premium_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_user_table',
            name='receipt_date',
            field=models.DateField(blank=True, default='2001-11-1', null=True),
        ),
    ]
