# Generated by Django 4.2 on 2023-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_alter_premium_user_table_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_user_table',
            name='death_flag',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
        migrations.AlterField(
            model_name='premium_user_table',
            name='death_flag',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
    ]
