# Generated by Django 4.2 on 2023-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_main_user_table_death_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_user_table',
            name='receipt_date',
            field=models.DateField(default='2001-11-1'),
        ),
    ]
